version: "3.8"

services:
  next-app:
      container_name: next-app
      build:
        context: ./
        dockerfile: dev.Dockerfile
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        #NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      volumes:
        - ./:/app
      restart: always
      ports:
        - 4000:3000
  db:
    image: postgres:10
    restart: always
    container_name: bausenberg-check-in-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'

    #volumes:
     # - ./db:/data/db:rw
     # - db
