version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: bausenberg-check-in-client
    container_name: bausenberg-check-in-client
    restart: always
    ports:
      - "80:80"

  # server:
  #   image: node:16.2.0-alpine3.13
  #   restart: always
  #   container_name: bausenberg-check-in-server

  #   working_dir: /bausenberg-check-in/server
  #   volumes:
  #     - ./:/bausenberg-check-in:rw
  #   environment:
  #     # - NODE_ENV=production

  #   command: ./docker-entrypoint.sh
# networks:
#   default:
#     external:
#       name: traefik
