version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: bausenberg-check-in-client
    container_name: bausenberg-check-in-client
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.bausenberg-check-in.rule: "Host(`bausenberg-check-in.stephanschoepe.de`)"
      traefik.http.routers.bausenberg-check-in.entrypoints: websecure
      traefik.http.routers.bausenberg-check-in.tls.certresolver: myresolver
      traefik.http.routers.bausenberg-check-in.priority: 100
      traefik.docker.network: traefik

  server:
    image: node:16.2.0-alpine3.13
    restart: always
    container_name: bausenberg-check-in-server

    working_dir: /bausenberg-check-in/server
    volumes:
      - ./:/bausenberg-check-in:rw
    environment:
      - NODE_ENV=production
    labels:
      traefik.enable: true
      traefik.http.routers.bausenberg-check-in-ws.rule: "Host(`bausenberg-check-in.stephanschoepe.de`)"
      traefik.http.routers.bausenberg-check-in-ws.entrypoints: websecure
      traefik.http.routers.bausenberg-check-in-ws.tls.certresolver: myresolver
      traefik.http.services.bausenberg-check-in-ws.loadbalancer.server.port: 3031
      traefik.http.routers.bausenberg-check-in-ws.priority: 200
      traefik.docker.network: traefik
    command: ./docker-entrypoint.sh

networks:
  default:
    external:
      name: traefik
