version: "3.8"

services:
  next-app:
      container_name: next-app
      build:
        context: ./
        dockerfile: dev.Dockerfile
      environment:
        MONGO_ROOT_USER: ${MONGO_ROOT_USER}
        MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        #NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      volumes:
        - ./:/app
#        - ./:/app
      restart: always
      ports:
        - 4000:3000
  db:
    image: mongo:4.4.10
    restart: always
    container_name: bausenberg-check-in-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

    #volumes:
     # - ./db:/data/db:rw
     # - db
