import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { FormEvent } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    const landing = event.target.landing.value as HTMLInputElement;
    const data = {
      landing: event.target?.landing.value as HTMLInputElement,
    };

    const endpoint = "/api/check-out";

    const options = {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    };

    const res = await fetch(endpoint, options);
    console.log(res);

    if (res.status === 201) router.push("/thank-you");

    const result = await res.json();
    console.log(result);
  };
  return (
    <>
      <Head>
        <title>Bausenberg Check-in</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h3>Bausenberg Check-out</h3>
          <form onSubmit={handleSubmit}>
            <fieldset>
              <label htmlFor="btn-regular-landing">
                <input
                  id="btn-regular-landing"
                  type="radio"
                  name="landing"
                  value="Landewiese"
                />
                Landewiese 👌
              </label>

              <label htmlFor="btn-alternate-landing">
                <input
                  id="btn-alternate-landing"
                  type="radio"
                  name="landing"
                  value="Notlandewiese"
                />
                Notlandewiese 🧐
              </label>

              <label htmlFor="btn-xc-landing">
                <input
                  id="btn-xc-landing"
                  type="radio"
                  name="landing"
                  value="Streckenflug"
                />
                Streckenflug 🎉
              </label>

              <label htmlFor="btn-no-takeoff">
                <input
                  id="btn-no-takeoff"
                  type="radio"
                  name="landing"
                  value="Doch nicht gestartet"
                />
                Doch nicht gestartet 🤷
              </label>
            </fieldset>

            <button>Check out</button>
          </form>
        </div>
      </main>
    </>
  );
}
