# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: password
  NEXTAUTH_URL: http://localhost:3000/
  NEXTAUTH_SECRET: fb3qi8rzabdszi8q27neqow8han87rhcnw
  CHECKIN_RATE_LIMIT: 2
  DATABASE_URL: ${{ secrets.DB_TEST_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Generate prisma scheme
        run: yarn prisma generate

      - name: Push prisma schema to db
        run: yarn prisma db push

      - name: Seed DB test data
        run: yarn prisma db seed

      - name: Build next.js server
        run: yarn build

      - name: Start next.js server
        run: yarn start

      - name: Run tests
        run: yarn test
