#Checkins


###
POST http://localhost:3031/api/checkin HTTP/1.1
content-type: application/json

{
    "name": "Pilot 1",
    "club": "RML"
}

###
PUT http://localhost:3031/api/checkin/615e15f897ee4631ca3fc037 HTTP/1.1
content-type: application/json

{
    "landing": "XC"
}

###
GET http://localhost:3031/api/checkin
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEzMzJiMmQxLTJmNDctNGMwOS1jMWQ4LTFhOGYzZDVlOWE4ZSIsImlhdCI6MTYyMzI2ODM1NiwiZXhwIjoxNjIzMjY4NDU2fQ.eg1xTXDUBb6OqJH103ay8p4FCqNw4NCmuVYuaaEic8c




