#Check-ins


###
POST http://localhost:3031/api/check-in HTTP/1.1
content-type: application/json

{
    "name": "Pilot 1",
    "club": "RML"
}

###
PUT http://localhost:3031/api/check-out/615e15f897ee4631ca3fc037 HTTP/1.1
content-type: application/json

{
    "landing": "XC"
}




